# What is Numpy

NumPy is the fundamental package for scientific computing with Python. 
It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. 
It is implemented in C and Fortran so when calculations are **vectorized**, performance is very good.

So, in a nutshell:

* a powerful Python extension for N-dimensional array
* a tool for integrating C/C++ and Fortran code
* designed for scientific computation: linear algebra and Signal Analysis

If you are a MATLAB&reg; user we recommend to read [Numpy for MATLAB Users](http://www.scipy.org/NumPy_for_Matlab_Users) and [Benefit of Open Source Python versus commercial packages](http://www.scipy.org/NumPyProConPage). 

I'm a supporter of the **Open Science Movement**, thus I humbly suggest you to take a look at the [Science Code Manifesto](http://sciencecodemanifesto.org/)

# Getting Started with Numpy Arrays

NumPy's main object is the **homogeneous** ***multidimensional array***. It is a table of elements (usually numbers), all of the same type. 

In Numpy dimensions are called **axes**. 

The number of axes is called **rank**. 

The most important attributes of an ndarray object are:

* **ndarray.ndim**     - the number of axes (dimensions) of the array. 
* **ndarray.shape**    - the dimensions of the array. For a matrix with n rows and m columns, shape will be (n,m). 
* **ndarray.size**     - the total number of elements of the array. 
* **ndarray.dtype**    - numpy.int32, numpy.int16, and numpy.float64 are some examples. 
* **ndarray.itemsize** - the size in bytes of elements of the array. For example, elements of type float64 has itemsize 8 (=64/8) 

To use `numpy` need to import the module it using of example:

In [ ]:
import numpy as np  # naming import convention

### Terminology Assumption

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 

### Reference Documentation

* On the web: [http://docs.scipy.org](http://docs.scipy.org)/

* Interactive help:

If you're looking for something

In [ ]:
np.lookfor('create array')

In [ ]:
np.con*?

#### Help is your friend

Whenever in doubt, there is the `help` function to the rescue

In [ ]:
# For example, try 
help(np.ndarray)

## Numpy Array Object

`NumPy` has a multidimensional array object called ndarray. It consists of two parts as follows:
   
   * The actual data
   * Some metadata describing the data
    
    
The majority of array operations leave the raw data untouched. The only aspect that changes is the metadata.

<img src="./images/ndarray_with_details.png" />

## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [ ]:
v = np.array([1,2,3,4])
v

In [ ]:
M = np.array([[1., 2], [3.2, 4]])
M

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [ ]:
print('Type of v: ', type(v))
print('Type of M: ', type(M))

The difference between the `v` and `M` arrays is only their shapes. 

To do so, we could use the `numpy.shape` function:

In [ ]:
print('Shape of v: ', np.shape(v))
print('Shape of M: ', M.shape)

Alternatively, We can get information about the shape of an array by using the `ndarray.shape` **property** :

In [ ]:
v.shape, M.shape

Equivalently, we can get information about the **size** of the two `ndarrays`, namely the *total number of elements* in the array.

In [ ]:
print('Size of v:', v.size)
print('Size of M:', M.size)

#### More properties of the `numpy array`

In [ ]:
M.itemsize # bytes per element

In [ ]:
M.nbytes # number of bytes

In [ ]:
M.ndim # number of dimensions

In [ ]:
M.dtype

## Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. 

Instead we can use one of the many **functions** in `numpy` that generates arrays of different forms. 

Some of the more common are: 

* `np.arange`; 
* `np.linspace`; 
* `np.logspace`; 
* `np.mgrid`;
* `np.random.rand`;
* `np.diag`;
* `np.zeros`;
* `np.ones`;
* `np.empty`;
* `np.tile`.

### `np.arange`

In [ ]:
x = np.arange(0, 10, 1) 
print(x)

In [ ]:
# floating point step-wise range generatation
x = np.arange(-1, 1, 0.1)  
print(x)

### `np.linspace` and `np.logspace`

In [ ]:
# using linspace, both end points **ARE included**
np.linspace(0, 10, 25)

In [ ]:
np.logspace(0, np.e**2, 10, base=np.e)

### `np.random.rand` & `np.random.randn`

In [ ]:
# uniform random numbers in [0,1]
np.random.rand(5,5)

In [ ]:
# standard normal distributed random numbers
np.random.randn(5,5)

### `np.diag`

In [ ]:
# a diagonal matrix
np.diag([1,2,3])

In [ ]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=1) 

### `np.eye`

In [ ]:
# a diagonal matrix with ones on the main diagonal
np.eye(3)  # 3 is the 

### `np.zeros` and `np.ones`

In [ ]:
np.zeros((3,3))

In [ ]:
np.ones((3, 3))

# Exercise

***Try by yourself*** the following commands:

    np.zeros((3,4))
    np.ones((3,4))
    np.empty((2,3))
    np.eye(5)
    np.diag(np.arange(5))
    np.tile(np.array([[6, 7], [8, 9]]), (2, 2))

## So, why is it useful then?

So far the `numpy.ndarray` looks awefully much like a Python **list** (or **nested list**). 

*Why not simply use Python lists for computations instead of creating a new array type?*

There are several reasons:

* Python lists are very general. 
    - They can contain any kind of object. 
    - They are dynamically typed. 
    - They do not support mathematical functions such as matrix and dot multiplications, etc. 
    - Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
    
    
* Numpy arrays are **statically typed** and **homogeneous**. 
    - The type of the elements is determined when array is created.
    
    
* Numpy arrays are memory efficient.
    - Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

### Python Implementation

In [ ]:
import numpy as np

In [ ]:
L = range(1000)

In [ ]:
%timeit [i**2 for i in L]

### (Kind-of the same) in Numpy Code

In [ ]:
a = np.arange(1000)

In [ ]:
%timeit a**2

### The **Wrong** way to do it

In [ ]:
%timeit [element**2 for element in a]

This is the wrong way to use Numpy: iterating a `ndarray` explicitly causes you to lose all the performance gain provided by Numpy. 
This is mainly due to many causes - especially caused by the fact that the `for loop` operation is performed at _Python-level_ rather than
at _C-level_ as performed internally by Numpy

## Exercises

### Simple arrays

* Create simple one and two dimensional arrays. First, redo the examples
from above. And then create your own.

* Use the functions `len`, `shape` and `ndim` on some of those arrays and
observe their output.

### Creating arrays using functions

* Experiment with `arange`, `linspace`, `ones`, `zeros`, `eye` and `diag`.

* Create different kinds of arrays with random numbers.

* Try setting the seed before creating an array with random values 
    - *hint*: use `np.random.seed`

* Look at the function `np.empty`. What does it do? When might this be
useful?

# Basic Data Type

You may have noticed that, in some instances, array elements are
displayed with a trailing dot (e.g. `2.` vs `2`). This is due to a
difference in the data-type used:

In [ ]:
a = np.array([1, 2, 3])
a.dtype

In [ ]:
a = np.array([1., 2., 3.])
a.dtype

### Note

Different data-types allow us to store data more compactly in memory,
but most of the time we simply work with floating point numbers. Note
that, in the example above, NumPy auto-detects the data-type from the
input.

You can explicitly specify which data-type you want:

In [ ]:
c = np.array([1, 2, 3], dtype=float)
c.dtype

The **default** data type is floating point:

In [ ]:
a = np.ones((3, 3))
a.dtype

## Basic Data Types

    bool             | This stores boolean (True or False) as a bit

    inti             | This is a platform integer (normally either int32 or int64)
    int8             | This is an integer ranging from -128 to 127
    int16            | This is an integer ranging from -32768 to 32767
    int32            | This is an integer ranging from -2 ** 31 to 2 ** 31 -1
    int64            | This is an integer ranging from -2 ** 63 to 2 ** 63 -1
    
    uint8            | This is an unsigned integer ranging from 0 to 255
    uint16           | This is an unsigned integer ranging from 0 to 65535
    uint32           | This is an unsigned integer ranging from 0 to 2 ** 32 - 1
    uint64           | This is an unsigned integer ranging from 0 to 2 ** 64 - 1

    float16          | This is a half precision float with sign bit, 5 bits exponent, and 10 bits mantissa
    float32          | This is a single precision float with sign bit, 8 bits exponent, and 23 bits mantissa
    float64 or float | This is a double precision float with sign bit, 11 bits exponent, and 52 bits mantissa
    complex64        | This is a complex number represented by two 32-bit floats (real and imaginary components)
    complex128       | This is a complex number represented by two 64-bit floats (real and imaginary components)
    (or complex)


## Numerical Types and Representation

The **numerical dtype** of an array should be selected very carefully, as it directly affects the numerical representation of elements, that is: 

   * the number of **bytes used; 
   * the *numerical range*

So, then: **What happens if I try to represent a number that is Out of range?**

Let's have a go with **integers**, i.e., `int8` and `uint8`

In [ ]:
x = np.zeros(4, 'int8')  # Integer ranging from -128 to 127
x

In [ ]:
x[0] = 127
x

In [ ]:
x[0] = 128
x

In [ ]:
x[1] = 129
x

In [ ]:
x[2] = 257  # i.e. (128 x 2) + 1
x

In [ ]:
ux = np.zeros(4, 'uint8')  # Integer ranging from 0 to 255
ux

In [ ]:
ux[0] = 255
ux[1] = 256
ux[2] = 257
ux[3] = 513  # (256 x 2) + 1
ux

---

# Exercises - Basic Numpy

## Ex 1. Create an array containing integers from $2$ to $2^6$

#### Hint: use Python `range` function

## 1.1 Print `ndarray` attributes and properties
(e.g. `type`, `dtype`, `shape...`) using previous on

## Ex 2. Create a 3x3 Matrix array and fill it with integer numbers

## Ex3: Create a Matrix of any size and fill it with random numbers

### HInt: take a look at `numpy.random.rand`

## Array-generating Functions

## Ex 1. Create an array containing integers from $2$ to $2^6$

#### Hint: use Python `range` function

## 1.1 Print `ndarray` attributes and properties
(e.g. `type`, `dtype`, `shape...`) using previous on

## Ex 2. Create a 3x3 Matrix array and fill it with integer numbers

## Ex3: Create a Matrix of any size and fill it with random numbers

### HInt: take a look at `numpy.random.rand`

---

# Linear algebra

**Vectorizing** code is the key to writing efficient numerical calculation with Python/Numpy. 

That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like **matrix-matrix multiplication**.

In [7]:
import numpy as np

## Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [8]:
v1 = np.arange(0, 5)

In [9]:
v1 * 2

array([0, 2, 4, 6, 8])

In [10]:
v1 + 2

array([2, 3, 4, 5, 6])

In [11]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

In [12]:
print('A * 2: ', '\n', A * 2)
print('A + 2: ', '\n', A + 2)

A * 2:  
 [[ 0  2  4  6  8]
 [20 22 24 26 28]
 [40 42 44 46 48]
 [60 62 64 66 68]
 [80 82 84 86 88]]
A + 2:  
 [[ 2  3  4  5  6]
 [12 13 14 15 16]
 [22 23 24 25 26]
 [32 33 34 35 36]
 [42 43 44 45 46]]


## Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [13]:
A * A # element-wise multiplication

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [14]:
v1 * v1

array([ 0,  1,  4,  9, 16])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [15]:
A.shape, v1.shape

((5, 5), (5,))

In [16]:
A * v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

## Matrix algebra

What about **matrix mutiplication**? 

There are two ways. 

We can either use the `np.dot` function, which applies a **matrix-matrix**, **matrix-vector**, or **inner vector multiplication** to its two arguments: 

In [17]:
np.dot(A, A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [18]:
np.dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [19]:
np.dot(v1, v1)

30

## A *new* dedicated Infix operator for Matrix Multiplication

**Python 3.5** (released on the **24th Aug.**) introduces a new binary operator to be used for matrix multiplication, called `@` . (Mnemonic: `@` is * for `mATrices`.)

Some useful hints:

- PEP465 Description: [https://www.python.org/dev/peps/pep-0465/#abstract]()
- [Motivations](https://www.python.org/dev/peps/pep-0465/#motivation)
- [Rationale for Specification Details](https://www.python.org/dev/peps/pep-0465/#rationale-for-specification-details)

---

# Exercises - Linear Algebra

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. 

That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

## Scalar-array operartions

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

## Ex 4.1 

Generate a matrix of any size. Then multiply each element by `2` and subtract `1`.

#### HInt: The most intuitive way to implement this is the right one!

## Ex 4.2

Generate two square matrix of random numbers and multiply them element wise.

#### Hint: The clues from the previous exercise also apply here!-)

## Ex 4.3

Execute the `dot` product between two randomly generated matrix of comparable shapes.

#### Hint: Since we are using Python 3 here, you should be aware of the `@` operator.. :)

## Ex 4.4

Generate a matrix of any size and create the transpose.

#### Hint: Guess the difference from `np.transpose` and `array.T`

## Ex 4.5

Generate a `ndarray` of any size and shape of random numbers and calculate some statistics (`mean`, `sum` along axis, `min`, `max`)


#### HInt: Clues in the text of the exercise !-)

---

# Indexing

### Setting up the data

In [ ]:
np.random.seed(42)  # Setting the random seed

In [ ]:
# a vector: the argument to the array function is a Python list
v = np.random.rand(10)
v

In [ ]:
# a matrix: the argument to the array function is a nested Python list
M = np.random.rand(10, 2)
M

We can index elements in an array using the square bracket and indices:

In [ ]:
# v is a vector, and has only one dimension, taking one index
v[0]

In [ ]:
# M is a matrix, or a 2 dimensional array, taking two indices 
M[1,1]

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [ ]:
M[1] 

The same thing can be achieved with using `:` instead of an index: 

In [ ]:
M[1,:] # row 1

In [ ]:
M[:,1] # column 1

We can assign new values to elements in an array using indexing:

In [ ]:
M[0,0] = 1

In [ ]:
M

In [ ]:
# also works for rows and columns
M[1,:] = 0
M[:,1] = -1

In [ ]:
M

## Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [ ]:
a = np.array([1,2,3,4,5])
a

In [ ]:
a[1:3]

Array slices are **mutable**: if they are assigned a new value the original array from which the slice was extracted is modified:

In [ ]:
a[1:3] = [-2,-3]

a

* We can omit any of the three parameters in `M[lower:upper:step]`:

In [ ]:
a[::] # lower, upper, step all take the default values

In [ ]:
a[::2] # step is 2, lower and upper defaults to the beginning and end of the array

In [ ]:
a[:3] # first three elements

In [ ]:
a[3:] # elements from index 3

* Negative indices counts from the end of the array (positive index from the begining):

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
a[-1] # the last element in the array

In [ ]:
a[-3:] # the last three elements

* Index slicing works exactly the same way for multidimensional arrays:

In [ ]:
A = np.array([[n+m*10 for n in range(5)] 
              for m in range(5)])
A

In [ ]:
# a block from the original array
A[1:4, 1:4]

In [ ]:
# strides
A[::2, ::2]

## Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [ ]:
row_indices = [1, 2, 3]
A[row_indices]

In [ ]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

* We can also index **masks**: 

    - If the index mask is an Numpy array of with data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position each element: 

In [ ]:
b = np.array([n for n in range(5)])
b

In [ ]:
row_mask = np.array([True, False, True, False, False])
b[row_mask]

* Alternatively:

In [ ]:
# same thing
row_mask = np.array([1,0,1,0,0], dtype=bool)
b[row_mask]

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [ ]:
x = np.arange(0, 10, 0.5)
x

In [ ]:
mask = (5 < x) * (x < 7.5)

mask

In [ ]:
x[mask]

Alternatively, we can use the condition (mask) array directly within brackets to index the array

In [ ]:
x[(5 < x) * (x < 7.5)]

---

# Exercises on Indexing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array

## Ex 3.1 

Generate a three-dimensional array of any size containing random numbers taken from an uniform distribution (_guess the numpy function in `np.random`_). Then print out separately the first entry along the three axis (i.e. `x, y, z`)  


#### Hint: Slicing with numpy arrays works quite like Python lists

## Ex 3.2

Create a vector and print out elements in reverse order

#### Hint: Use slicing for this exercise

## Ex 3.3

Generate a $7 \times 7$ matrix and replace all the elements in odd rows and even columns with `1`.

#### Hint: Use slicing to solve this exercise!

#### Note: Take a look at the original matrix, then.

## Ex 3.4 

Generate a `10 x 10` matrix of numbers `A`. Then, generate a numpy array of integers in range `1-9`. Pick `5` random values (with no repetition) from this array and use these values to extract rows from the original matrix `A`.

## Ex 3.5 

Repeat the previous exercise but this time extract columns from `A`

## Ex 3.6

Generate an array of numbers from `0` to `20` with step `0.5`. 
Extract all the values greater than a randomly generated number in the same range.

#### Hint: Try to write the condition as an expression and save it to a variable. Then, use this variable in square brackets to index.... this is when the magic happens!